name: Docker Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/wisecow:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/wisecow:latest
      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME}}/wisecow:latest
      - name: Tag Docker image for Kubernetes
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME}}/wisecow:latest 
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
